#!/usr/bin/env perl


use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Path::Class qw/dir file/;
use Data::Dumper;

use Kanku::Config;
use Kanku::Scheduler;
use openKanku::Schema;
use YAML;
use JSON::XS;

my $cfg = Kanku::Config->new()->config;

print Dumper($cfg);

my $cfg_file = file($FindBin::Bin,'..','config.yml');
my $cfg_content = $cfg_file->slurp;
my $cfg_yaml = YAML::Load($cfg_content);
my $schema = openKanku::Schema->connect($cfg_yaml->{plugins}->{DBIC}->{default}->{dsn});


my $scheduler = Kanku::Scheduler->new(schema=>$schema);
my $lr = $scheduler->get_last_run_result("obs-server",'Kanku::Handler::OBSDownload');
print Dumper(
  $lr->result(),
  $lr->state()
);

exit 0;
