#!/usr/bin/env perl
use strict;
use warnings;

BEGIN { unshift @::INC, ($ENV{KANKU_LIB_DIR} || '/usr/lib/kanku/lib'); }


use Kanku::Daemon::Scheduler;

Kanku::Daemon::Scheduler->new()->prepare_and_run();

exit 0;
