#!/usr/bin/env perl
use strict;
use warnings;

BEGIN { unshift @::INC, ($ENV{KANKU_LIB_DIR} || '/usr/lib/kanku/lib'); }

$::ENV{SSH_AUTH_SOCK} = q{};

use Kanku::Daemon::Worker;

Kanku::Daemon::Worker->new()->prepare_and_run();

exit 0;
